config/routes.rb
# frozen_string_literal: true

require 'subdomain'

Rails.application.routes.draw do
  constraints(Subdomain) do
    get '/', to: 'publics#show'
  end

  # get '/', to: '', constraints: { subdomain: /.+/ }
  resources :urls
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
# frozen_string_literal: true

class Url < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/publics_controller.rb
# frozen_string_literal: true

require 'net/http'
require 'uri'

class PublicsController < ApplicationController
  layout false

  TLKMDEV_REGEX = /\A[a-zA-Z0-9]+\.tlkm\.dev\z/

  # GET short_name.example.com
  def show
    @url = if request.host.match?(TLKMDEV_REGEX)
      Url.find_by(short_url: request.subdomain)
    elsif (matching_whole_host = Url.find_by(short_url: request.host))
      matching_whole_host
    else
      return render plain: 'Not found 🌚🌚', status: :not_found
    end

    response = Net::HTTP.get_response(URI.parse(@url.original_url))

    if %w[DENY SAMEORIGIN].include?(response['X-Frame-Options'])
      redirect_to @url.original_url, allow_other_host: true, status: :found
    else
      render template: 'publics/show'
    end
  end
end

app/controllers/urls_controller.rb
# frozen_string_literal: true

class UrlsController < ApplicationController
  before_action :set_url, only: %i[show edit update destroy]

  # GET /urls or /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1 or /urls/1.json
  # GET short_name.example.com
  def show; end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit; end

  # POST /urls or /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to url_url(@url), notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to url_url(@url), notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    @url.destroy

    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_url
    @url = Url.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def url_params
    params.require(:url).permit(:original_url, :short_url)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def hostname_de_admintrator(request)
    request.host.split('.').without('admin').join('.')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/publics/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      body, html {
        margin: 0;
        padding: 0;
        height: 100%;
        overflow: hidden;
      }

      #inliner {
        position: absolute;
        left: 0;
        width: 100%;
        height: 100%;
        border: none;
      }
    </style>
  </head>
  <body>
    <iframe id="inliner" src="<%= @url.original_url %>">"></iframe>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :original_url, style: "display: block" %>
    <%= form.text_field :original_url %>
  </div>

  <div>
    <%= form.label :short_url, style: "display: block" %>
    <%= form.text_field :short_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/_url.html.erb
<div id="<%= dom_id url %>">
  <p>
    <strong>Original url:</strong>
    <%= link_to url.original_url %>
  </p>

  <p>
    <strong>Short url:</strong>
    <% short_link = "#{request.protocol}#{url.short_url}.#{hostname_de_admintrator(request)}" %>
    <%= link_to short_link, short_link %>
  </p>

</div>

app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Show this url", @url %> |
  <%= link_to "Back to urls", urls_path %>
</div>

app/views/urls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Urls</h1>

<div id="urls">
  <% @urls.each do |url| %>
    <%= render url %>
    <p>
      <%= link_to "Edit/Delete this url", url %>
    </p>

    <hr />
  <% end %>
</div>

<%= link_to "New url", new_url_path %>

app/views/urls/new.html.erb
<h1>New url</h1>

<%= render "form", url: @url %>

<br>

<div>
  <%= link_to "Back to urls", urls_path %>
</div>

app/views/urls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= "ID: #{@url.id}: #{@url.original_url} → #{@url.short_url}" %>

<div>
  <%= link_to "Edit this url", edit_url_path(@url) %> |
  <%= link_to "Back to urls", urls_path %>

  <%= button_to "Destroy this url", @url, method: :delete %>
</div>